# Generated by Django 2.1.5 on 2020-03-24 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_auto_20200319_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name': 'qwe', 'verbose_name_plural': 'asd'},
        ),
    ]
