# Generated by Django 2.1.5 on 2020-03-24 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_auto_20200324_1903'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'verbose_name': 'Children'},
        ),
    ]
