# Generated by Django 2.1.5 on 2020-03-24 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0005_auto_20200324_1904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'verbose_name': 'Childd', 'verbose_name_plural': 'Children'},
        ),
    ]
